name: Sync from upstream

on:
  schedule:
    - cron: '*/30 * * * *'  # Cada 30 minutos
  workflow_dispatch:       # Permite ejecutarlo manualmente

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}
          ref: rama-develop-pre-presentacion

      - name: Set up Git
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"

      - name: Add upstream remote and fetch
        run: |
          git remote add upstream https://github.com/AxelOP96/backend-alquimia.git
          git fetch upstream

      - name: Merge upstream into fork
        run: |
          git merge upstream/rama-develop-pre-presentacion --no-edit || true
          git push origin rama-develop-pre-presentacion
