name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0,30 * * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout fork repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Add upstream remote
        run: git remote add upstream https://github.com/AxelOP96/backend-alquimia.git

      - name: Fetch upstream changes
        run: git fetch upstream

      - name: Merge upstream/main into fork/main
        run: |
          git checkout main
          git merge upstream/main --no-edit || echo "Nothing to merge"

      - name: Force a marker update
        run: |
          echo "Synced at $(date -u)" > sync-marker.txt
          git add sync-marker.txt
          git commit -m "Sync marker update [CI]" || echo "No changes to commit"

      - name: Push changes to fork
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
